### ISSUE TITLE
link to colab notebook

### ISSUE THREAD

**Issue by ak9250** [sinanatra/DCGAN-Art-Tensorflow#1]
Hi great job on this project, where is the link to the colab notebook as it was not in the files. I think it would be good to include it than having to open it in another new notebook and import the file.

**Comment by sinanatra** [comment]
uooops, here it is, https://colab.research.google.com/drive/18RglimpA1JH7bRbTXtxx9fAbDl60sFVQ#scrollTo=YLBwMdxMW3PR

**Comment by ak9250** [comment]
I am getting this error 
![screen shot 2018-12-14 at 6 42 21 pm](https://user-images.githubusercontent.com/6818285/50035482-49b9e480-ffd0-11e8-8293-f2275ea4fa0f.png)
to add my own folder how many images are suggested?

**Comment by ak9250** [comment]
thanks, it is working now but the connection keeps dropping and I have to reconnect multiple times, did you experience this?
![screen shot 2018-12-15 at 11 04 25 am](https://user-images.githubusercontent.com/6818285/50045096-5b949980-005b-11e9-9428-3590b050ee3a.png)
![screen shot 2018-12-15 at 11 06 38 am](https://user-images.githubusercontent.com/6818285/50045109-7e26b280-005b-11e9-8b72-be6a3bcff0e0.png)

**Comment by ak9250** [comment]
So I had to quit it as it was freezing my computer, it went through about 17/500 epochs before it completely froze and I had to force quit

**Comment by ak9250** [comment]
I set epoch to 10 and ran it again was able to get test_arrage2 download but got error at 18
![test_arange_2](https://user-images.githubusercontent.com/6818285/50050067-7b5da900-00bf-11e9-9108-fb7aaf5e8291.png)
![screen shot 2018-12-15 at 11 15 36 pm](https://user-images.githubusercontent.com/6818285/50050069-7f89c680-00bf-11e9-8e1a-a6bc4bc5be05.png)

**Comment by sinanatra** [comment]
so, for the connection dropping, what are your paramethers: batch size etc?
Google colab it's a great and free resource but does not handle huge chunks ( i usually have batches max at 128 / 256 ) - you can also check how much free memory the gpu has
````
import GPUtil as GPU
GPUs = GPU.getGPUs()
# XXX: only one GPU on Colab and isn’t guaranteed
gpu = GPUs[0]
def printm():
 process = psutil.Process(os.getpid())
 print("Gen RAM Free: " + humanize.naturalsize( psutil.virtual_memory().available ), " I Proc size: " + humanize.naturalsize( process.memory_info().rss))
 print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
printm()
```

check how many samples there are
```
import os
os.listdir('./samples')
```
and in the test command try to change these values:
` --option 3`

**Comment by sinanatra** [comment]
it keeps on saving, and always continues - if you generate checkpoints, i.e.
```
[*] Reading checkpoints...
 [*] Success to read DCGAN.model-2002 <-- here you see it
```
The counter anyway always reset from 0
` Epoch: [ 0/10] [   0/ 228] time: 10.5644, d_loss: 126.43296051, g_loss: 0.00000000 `

**Comment by ak9250** [comment]
ok thanks, are you able to look at the colab notebook I linked I am using the same parameters now that you have used i think I might have to set the checkpoint havent done that before.

**Comment by ak9250** [comment]
ok so this is what I get for checkpoints
![screen shot 2018-12-16 at 2 17 30 pm](https://user-images.githubusercontent.com/6818285/50057798-6fb0c780-013d-11e9-83c2-460124c8abc7.png)

**Comment by ak9250** [comment]
noticed this one most recent run 
![screen shot 2018-12-16 at 2 33 33 pm](https://user-images.githubusercontent.com/6818285/50057936-9ff96580-013f-11e9-8e3f-fe6dc797c3d5.png)
but it still runs the next line and downloaded test_arrage_2
![test_arange_2 1](https://user-images.githubusercontent.com/6818285/50057942-ae478180-013f-11e9-9dc9-9cbd189d7b07.png)

**Comment by ak9250** [comment]
I can see the checkpoints now
![screen shot 2018-12-17 at 11 46 12 am](https://user-images.githubusercontent.com/6818285/50101748-68e38c80-01f1-11e9-9204-ff87b69f1b76.png)
100 epoch with batch size 256
![test_arange_2 5](https://user-images.githubusercontent.com/6818285/50101775-739e2180-01f1-11e9-87a2-cc6873fc2127.png)

**Comment by sinanatra** [comment]
the linked datasets are folders on my Google Drive, you just have to create it on yours, place it on Drive, share the link and copy the last part.
To do the datasets i used, i made an ipython notebook to scrape from wikiArt `https://github.com/sinanatra/DCGAN-Art-Tensorflow/blob/master/wikiart_scraper.ipynb`

**Comment by ak9250** [comment]
im not sure if anything has changed, I got the images dataset that I wanted to use 69 images and it is on the drive. I copied the link but it is not working for me. I then saved a copy of your notebook again to run it and got this error which I didnt get before
![screen shot 2018-12-27 at 11 43 37 pm](https://user-images.githubusercontent.com/6818285/50502970-4e9b8100-0a31-11e9-81ba-dc826df05b88.png)

**Comment by ak9250** [comment]
noticed it is ignoring unzip for that link
![screen shot 2018-12-28 at 10 17 04 pm](https://user-images.githubusercontent.com/6818285/50532917-5e2ccf80-0aee-11e9-91c1-276e347b92a8.png)

**Comment by ak9250** [comment]
my folder was not zipped before adding the link which solved the issue
@sinanatra have you seen this before, i was able to get 50 epochs finished but at 100 epochs it went from busy to connected and frozen
![screen shot 2018-12-31 at 7 02 32 pm](https://user-images.githubusercontent.com/6818285/50569276-73447100-0d2f-11e9-9dcb-722f5753e727.png)

**Comment by sinanatra** [comment]
@ak9250 colab restarts its virtual machines every 24 hours i guess, that might have happened. To avoid it i would save the checkpoints on Drive. Or sometimes it happens, when there is not enough ram. I always check it with 
```
import tensorflow as tf
tf.test.gpu_device_name()
```
